/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPoolFactory, IPoolFactoryInterface } from "../IPoolFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "poolCode",
        type: "string",
      },
    ],
    name: "DeployPool",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "string",
            name: "poolCode",
            type: "string",
          },
          {
            internalType: "uint32",
            name: "frontRunningInterval",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "updateInterval",
            type: "uint32",
          },
          {
            internalType: "bytes16",
            name: "fee",
            type: "bytes16",
          },
          {
            internalType: "uint16",
            name: "leverageAmount",
            type: "uint16",
          },
          {
            internalType: "address",
            name: "feeAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "quoteToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "oracleWrapper",
            type: "address",
          },
        ],
        internalType: "struct IPoolFactory.PoolDeployment",
        name: "deploymentParameters",
        type: "tuple",
      },
    ],
    name: "deployPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPoolFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolFactoryInterface {
    return new utils.Interface(_abi) as IPoolFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoolFactory {
    return new Contract(address, _abi, signerOrProvider) as IPoolFactory;
  }
}
