/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IPoolCommitterInterface extends ethers.utils.Interface {
  functions: {
    "commit(uint8,uint112)": FunctionFragment;
    "executeAllCommitments()": FunctionFragment;
    "executeCommitment(tuple)": FunctionFragment;
    "getCommit(uint128)": FunctionFragment;
    "setQuoteAndPool(address,address)": FunctionFragment;
    "uncommit(uint128)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "commit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeAllCommitments",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeCommitment",
    values: [
      {
        amount: BigNumberish;
        commitType: BigNumberish;
        created: BigNumberish;
        owner: string;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setQuoteAndPool",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "uncommit",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "commit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeAllCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCommit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setQuoteAndPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uncommit", data: BytesLike): Result;

  events: {
    "CreateCommit(uint128,uint128,uint8)": EventFragment;
    "ExecuteCommit(uint128)": EventFragment;
    "FailedCommitExecution(uint128)": EventFragment;
    "RemoveCommit(uint128,uint128,uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreateCommit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecuteCommit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FailedCommitExecution"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemoveCommit"): EventFragment;
}

export class IPoolCommitter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IPoolCommitterInterface;

  functions: {
    commit(
      commitType: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeAllCommitments(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeCommitment(
      _commit: {
        amount: BigNumberish;
        commitType: BigNumberish;
        created: BigNumberish;
        owner: string;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCommit(
      _commitID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, number, number, string] & {
          amount: BigNumber;
          commitType: number;
          created: number;
          owner: string;
        }
      ]
    >;

    setQuoteAndPool(
      quoteToken: string,
      leveragedPool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    uncommit(
      commitID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  commit(
    commitType: BigNumberish,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeAllCommitments(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeCommitment(
    _commit: {
      amount: BigNumberish;
      commitType: BigNumberish;
      created: BigNumberish;
      owner: string;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCommit(
    _commitID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number, number, string] & {
      amount: BigNumber;
      commitType: number;
      created: number;
      owner: string;
    }
  >;

  setQuoteAndPool(
    quoteToken: string,
    leveragedPool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  uncommit(
    commitID: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    commit(
      commitType: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    executeAllCommitments(overrides?: CallOverrides): Promise<void>;

    executeCommitment(
      _commit: {
        amount: BigNumberish;
        commitType: BigNumberish;
        created: BigNumberish;
        owner: string;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    getCommit(
      _commitID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, number, string] & {
        amount: BigNumber;
        commitType: number;
        created: number;
        owner: string;
      }
    >;

    setQuoteAndPool(
      quoteToken: string,
      leveragedPool: string,
      overrides?: CallOverrides
    ): Promise<void>;

    uncommit(commitID: BigNumberish, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    CreateCommit(
      commitID?: BigNumberish | null,
      amount?: BigNumberish | null,
      commitType?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, number],
      { commitID: BigNumber; amount: BigNumber; commitType: number }
    >;

    ExecuteCommit(
      commitID?: null
    ): TypedEventFilter<[BigNumber], { commitID: BigNumber }>;

    FailedCommitExecution(
      commitID?: null
    ): TypedEventFilter<[BigNumber], { commitID: BigNumber }>;

    RemoveCommit(
      commitID?: BigNumberish | null,
      amount?: BigNumberish | null,
      commitType?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber, number],
      { commitID: BigNumber; amount: BigNumber; commitType: number }
    >;
  };

  estimateGas: {
    commit(
      commitType: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeAllCommitments(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeCommitment(
      _commit: {
        amount: BigNumberish;
        commitType: BigNumberish;
        created: BigNumberish;
        owner: string;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCommit(
      _commitID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setQuoteAndPool(
      quoteToken: string,
      leveragedPool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    uncommit(
      commitID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    commit(
      commitType: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeAllCommitments(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeCommitment(
      _commit: {
        amount: BigNumberish;
        commitType: BigNumberish;
        created: BigNumberish;
        owner: string;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCommit(
      _commitID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setQuoteAndPool(
      quoteToken: string,
      leveragedPool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    uncommit(
      commitID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
