/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC20DecimalsWrapper,
  IERC20DecimalsWrapperInterface,
} from "../IERC20DecimalsWrapper";

const _abi = [
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IERC20DecimalsWrapper__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20DecimalsWrapperInterface {
    return new utils.Interface(_abi) as IERC20DecimalsWrapperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC20DecimalsWrapper {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC20DecimalsWrapper;
  }
}
