/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPoolCommitterDeployer,
  IPoolCommitterDeployerInterface,
} from "../IPoolCommitterDeployer";

const _abi = [
  {
    inputs: [],
    name: "deploy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPoolCommitterDeployer__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolCommitterDeployerInterface {
    return new utils.Interface(_abi) as IPoolCommitterDeployerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoolCommitterDeployer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPoolCommitterDeployer;
  }
}
