/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IPoolKeeperInterface extends ethers.utils.Interface {
  functions: {
    "checkUpkeepMultiplePools(address[])": FunctionFragment;
    "checkUpkeepSinglePool(address)": FunctionFragment;
    "newPool(address)": FunctionFragment;
    "performUpkeepMultiplePools(address[])": FunctionFragment;
    "performUpkeepSinglePool(address)": FunctionFragment;
    "setFactory(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkUpkeepMultiplePools",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "checkUpkeepSinglePool",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "newPool", values: [string]): string;
  encodeFunctionData(
    functionFragment: "performUpkeepMultiplePools",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "performUpkeepSinglePool",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setFactory", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "checkUpkeepMultiplePools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkUpkeepSinglePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeepMultiplePools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeepSinglePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFactory", data: BytesLike): Result;

  events: {
    "ExecutePriceChange(int256,int256,uint32,address)": EventFragment;
    "NewRound(int256,int256,uint32,address)": EventFragment;
    "PoolAdded(address,int256,address)": EventFragment;
    "PoolUpdateError(address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ExecutePriceChange"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewRound"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PoolAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PoolUpdateError"): EventFragment;
}

export class IPoolKeeper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IPoolKeeperInterface;

  functions: {
    checkUpkeepMultiplePools(
      poolCodes: string[],
      overrides?: CallOverrides
    ): Promise<[boolean] & { upkeepNeeded: boolean }>;

    checkUpkeepSinglePool(
      poolCode: string,
      overrides?: CallOverrides
    ): Promise<[boolean] & { upkeepNeeded: boolean }>;

    newPool(
      _poolAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    performUpkeepMultiplePools(
      poolCodes: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    performUpkeepSinglePool(
      poolCode: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFactory(
      _factory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  checkUpkeepMultiplePools(
    poolCodes: string[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  checkUpkeepSinglePool(
    poolCode: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  newPool(
    _poolAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  performUpkeepMultiplePools(
    poolCodes: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  performUpkeepSinglePool(
    poolCode: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFactory(
    _factory: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    checkUpkeepMultiplePools(
      poolCodes: string[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    checkUpkeepSinglePool(
      poolCode: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    newPool(_poolAddress: string, overrides?: CallOverrides): Promise<void>;

    performUpkeepMultiplePools(
      poolCodes: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    performUpkeepSinglePool(
      poolCode: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setFactory(_factory: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    ExecutePriceChange(
      oldPrice?: BigNumberish | null,
      newPrice?: BigNumberish | null,
      updateInterval?: BigNumberish | null,
      pool?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, number, string],
      {
        oldPrice: BigNumber;
        newPrice: BigNumber;
        updateInterval: number;
        pool: string;
      }
    >;

    NewRound(
      oldPrice?: BigNumberish | null,
      newPrice?: BigNumberish | null,
      updateInterval?: BigNumberish | null,
      poolCode?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, number, string],
      {
        oldPrice: BigNumber;
        newPrice: BigNumber;
        updateInterval: number;
        poolCode: string;
      }
    >;

    PoolAdded(
      poolAddress?: string | null,
      firstPrice?: BigNumberish | null,
      poolCode?: null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { poolAddress: string; firstPrice: BigNumber; poolCode: string }
    >;

    PoolUpdateError(
      pool?: null,
      reason?: null
    ): TypedEventFilter<[string, string], { pool: string; reason: string }>;
  };

  estimateGas: {
    checkUpkeepMultiplePools(
      poolCodes: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkUpkeepSinglePool(
      poolCode: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    newPool(
      _poolAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    performUpkeepMultiplePools(
      poolCodes: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    performUpkeepSinglePool(
      poolCode: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFactory(
      _factory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkUpkeepMultiplePools(
      poolCodes: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkUpkeepSinglePool(
      poolCode: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    newPool(
      _poolAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    performUpkeepMultiplePools(
      poolCodes: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    performUpkeepSinglePool(
      poolCode: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFactory(
      _factory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
