name: Test
on:
  pull_request:
    branches:
      - release-v2 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run build 
      run: yarn build
    - name: Run tests
      run: yarn test --coverage
